# Generated by Django 3.1.7 on 2021-04-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210325_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Perú'), ('USD', 'United States')], default='PEN', max_length=30),
        ),
    ]
