# Generated by Django 3.1.7 on 2021-04-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210407_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_ext',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productext'),
        ),
    ]
