# Generated by Django 3.1.7 on 2021-04-07 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_data_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data_ext',
        ),
        migrations.AddField(
            model_name='productext',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
